instructor = User.first
student1 = User.second
student2 = User.third
student3 = User.fourth
student4 = User.create!(email: "user1@example.com", fname: "Marjie", lname: "Lam", role: "student", password: "abc123")
student5 = User.create!(email: "user2@example.com", fname: "Ellie", lname: "Redding", role: "student", password: "abc123")
student6 = User.create!(email: "user3@example.com", fname: "Jason", lname: "Langsner", role: "student", password: "abc123")
student7 = User.create!(email: "user4@example.com", fname: "Ryan", lname: "Particka", role: "student", password: "abc123")
student8 = User.create!(email: "user5@example.com", fname: "Jon", lname: "Loewy", role: "student", password: "abc123")
student9 = User.create!(email: "user6@example.com", fname: "Carly", lname: "Fox", role: "student", password: "abc123")
student10 = User.create!(email: "user7@example.com", fname: "Elana", lname: "Fox", role: "student", password: "abc123")

course1 = Course.create!(name: "Aerial Silks Level 1", description: "This is a beginner aerial silks course. No prior knowledge required")
course2 = Course.create!(name: "Aerial Silks Level 2", description: "This is an intermediate aerial silks course. Students must have completed a full session of Level 1.")
course3 = Course.create!(name: "Aerial Silks Level 3", description: "This is an advanced aerial silks course. Students be able to complete several drops in the air and be comfortable in the air for several minutes at a time.")
course4 = Course.create!(name: "Hula Hoop Level 1", description: "This is a free flow jam. You can bring any props you want and flow to the music")
course5 = Course.create!(name: "Aerial Conditioning", description: "Daily strength training. We will move through different apparatus and work our arms, core, and legs. Get ready to work!")
course6 = Course.create!(name: "Trapeze level 2", description: "This series is for students who have successfully completed a full series of trapeze level 1. You must be able to hang off the bar for 15 seconds and do a pullover without tagging")
course7 = Course.create!(name: "German Wheel Level 1", description: "German Wheel (or gym wheel) comes in 3 forms - straightline, spiral, and vault. We will experience beginner level tricks in all, specifically focusing on the fundamentals")

Registration.create!(user: instructor, course: course1)
Registration.create!(user: instructor, course: course2)
Registration.create!(user: instructor, course: course3)
Registration.create!(user: instructor, course: course4)
Registration.create!(user: instructor, course: course5)
Registration.create!(user: instructor, course: course6)
Registration.create!(user: instructor, course: course7)
Registration.create!(user: student1, course: course2)
Registration.create!(user: student1, course: course3)
Registration.create!(user: student1, course: course5)
Registration.create!(user: student2, course: course3)
Registration.create!(user: student2, course: course6)
Registration.create!(user: student2, course: course7)
Registration.create!(user: student3, course: course2)
Registration.create!(user: student3, course: course3)
Registration.create!(user: student3, course: course4)
Registration.create!(user: student3, course: course5)
Registration.create!(user: student4, course: course1)
Registration.create!(user: student4, course: course4)
Registration.create!(user: student4, course: course5)
Registration.create!(user: student4, course: course6)
Registration.create!(user: student5, course: course3)
Registration.create!(user: student5, course: course5)
Registration.create!(user: student5, course: course6)
Registration.create!(user: student5, course: course7)
Registration.create!(user: student6, course: course2)
Registration.create!(user: student6, course: course3)
Registration.create!(user: student6, course: course4)
Registration.create!(user: student6, course: course6)
Registration.create!(user: student7, course: course3)
Registration.create!(user: student7, course: course5)
Registration.create!(user: student8, course: course3)
Registration.create!(user: student8, course: course5)
Registration.create!(user: student9, course: course3)
Registration.create!(user: student9, course: course5)
Registration.create!(user: student10, course: course2)
Registration.create!(user: student10, course: course3)

individual_class2 = IndividualClass.create!(name: "Class 1", date: "2019/10/15", course: course3)
individual_class3 = IndividualClass.create!(name: "Class 2", date: "2019/10/22", course: course3)
individual_class4 = IndividualClass.create!(name: "Class 3", date: "2019/10/29", course: course3)
individual_class5 = IndividualClass.create!(name: "Class 4", date: "2019/11/05", course: course3)
individual_class6 = IndividualClass.create!(name: "Class 5", date: "2019/11/12", course: course3)
individual_class6 = IndividualClass.create!(name: "Class 6", date: "2019/11/19", course: course3)
individual_class8 = IndividualClass.create!(name: "Class 1", date: "2019/10/16", course: course2)
individual_class9 = IndividualClass.create!(name: "Class 2", date: "2019/10/23", course: course2)
individual_class10 = IndividualClass.create!(name: "Class 3", date: "2019/10/30", course: course2)
individual_class11 = IndividualClass.create!(name: "Class 4", date: "2019/11/06", course: course2)
individual_class12 = IndividualClass.create!(name: "Class 5", date: "2019/11/13", course: course2)
individual_class12 = IndividualClass.create!(name: "Class 6", date: "2019/11/20", course: course2)
individual_class8 = IndividualClass.create!(name: "Class 1", date: "2019/10/17", course: course1)
individual_class9 = IndividualClass.create!(name: "Class 2", date: "2019/10/24", course: course1)
individual_class10 = IndividualClass.create!(name: "Class 3", date: "2019/10/31", course: course1)
individual_class11 = IndividualClass.create!(name: "Class 4", date: "2019/11/07", course: course1)
individual_class12 = IndividualClass.create!(name: "Class 5", date: "2019/11/14", course: course1)
individual_class12 = IndividualClass.create!(name: "Class 6", date: "2019/11/21", course: course1)
individual_class8 = IndividualClass.create!(name: "Class 1", date: "2019/10/18", course: course4)
individual_class9 = IndividualClass.create!(name: "Class 2", date: "2019/10/25", course: course4)
individual_class10 = IndividualClass.create!(name: "Class 3", date: "2019/11/01", course: course4)
individual_class11 = IndividualClass.create!(name: "Class 4", date: "2019/11/08", course: course4)
individual_class12 = IndividualClass.create!(name: "Class 5", date: "2019/11/15", course: course4)
individual_class12 = IndividualClass.create!(name: "Class 6", date: "2019/11/22", course: course4)
individual_class8 = IndividualClass.create!(name: "Class 1", date: "2019/10/19", course: course5)
individual_class9 = IndividualClass.create!(name: "Class 2", date: "2019/10/26", course: course5)
individual_class10 = IndividualClass.create!(name: "Class 3", date: "2019/11/02", course: course5)
individual_class11 = IndividualClass.create!(name: "Class 4", date: "2019/11/09", course: course5)
individual_class12 = IndividualClass.create!(name: "Class 5", date: "2019/11/16", course: course5)
individual_class12 = IndividualClass.create!(name: "Class 6", date: "2019/11/23", course: course5)
individual_class8 = IndividualClass.create!(name: "Class 1", date: "2019/10/20", course: course6)
individual_class9 = IndividualClass.create!(name: "Class 2", date: "2019/10/27", course: course6)
individual_class10 = IndividualClass.create!(name: "Class 3", date: "2019/11/03", course: course6)
individual_class11 = IndividualClass.create!(name: "Class 4", date: "2019/11/10", course: course6)
individual_class12 = IndividualClass.create!(name: "Class 5", date: "2019/11/17", course: course6)
individual_class12 = IndividualClass.create!(name: "Class 6", date: "2019/11/24", course: course6)
individual_class8 = IndividualClass.create!(name: "Class 1", date: "2019/10/21", course: course7)
individual_class9 = IndividualClass.create!(name: "Class 2", date: "2019/10/28", course: course7)
individual_class10 = IndividualClass.create!(name: "Class 3", date: "2019/11/04", course: course7)
individual_class11 = IndividualClass.create!(name: "Class 4", date: "2019/11/11", course: course7)
individual_class12 = IndividualClass.create!(name: "Class 5", date: "2019/11/18", course: course7)
individual_class12 = IndividualClass.create!(name: "Class 6", date: "2019/11/25", course: course7)
